# Generated by Django 4.0.5 on 2022-06-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0003_rename_año_gameboy_anio_rename_año_nes_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sega',
            old_name='anio',
            new_name='año',
        ),
    ]
