# Generated by Django 4.0.5 on 2022-06-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0004_rename_anio_sega_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameboy',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='nes',
            old_name='anio',
            new_name='año',
        ),
    ]
