# Generated by Django 4.0.5 on 2022-08-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sega',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=300),
        ),
    ]
